export const LOAD_QUESTIONARIES_REQUEST = 'LOAD_QUESTIONARIES_REQUEST';
export const LOAD_QUESTIONARIES_SUCCESS = 'LOAD_QUESTIONARIES_SUCCESS';
export const LOAD_QUESTIONARIES_FAILURE = 'LOAD_QUESTIONARIES_FAILURE';

export const SELECT_QUESTIONARY = 'SELECT_QUESTIONARY';

export const LOAD_CURRENT_QUESTIONARY_REQUEST = 'LOAD_CURRENT_QUESTIONARY_REQUEST';
export const LOAD_CURRENT_QUESTIONARY_SUCCESS = 'LOAD_CURRENT_QUESTIONARY_SUCCESS';
export const LOAD_CURRENT_QUESTIONARY_FAILURE = 'LOAD_CURRENT_QUESTIONARY_FAILURE';
